import turtle

def turtleLetter(letter,tur):
    if letter=="box":
        tur.setheading(0)
        tur.forward(40)
        tur.right(90)
        tur.forward(60)
        tur.right(90)
        tur.forward(40)
        tur.right(90)
        tur.forward(60)

    elif letter == "A":
        tur.setheading(0)
        tur.pu()
        tur.fd(5)
        tur.right(90)
        tur.fd(5)
        tur.pd()
        tur.fd(30)
        tur.right(180)
        tur.fd(30)
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(30)
        tur.right(180)
        tur.fd(15)
        tur.left(90)
        tur.fd(20)
        tur.pu()
        #fixes
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(35)
        #tur.right(180)
    elif letter == "B":
        tur.setheading(0) 
        tur.pd()
        tur.right(90)
        tur.fd(25)
        tur.left(180)
        tur.fd(25)
        tur.right(90)
        tur.fd(25)
        tur.right(90)
        tur.fd(25)
        tur.right(90)
        tur.fd(25)
        tur.left(90)
        tur.fd(25)
        tur.left(90)
        tur.fd(25)
        tur.left(90)
        tur.fd(25)
    elif letter == "C":
        tur.setheading(0)
        tur.pd()
        tur.bk(25)
        tur.right(90)
        tur.fd(25)
        tur.left(90)
    elif letter == "D":
        tur.setheading(0)
        tur.pd()
        tur.fd(25)
        tur.right(90)
        tur.fd(25)
        tur.right(90)
        tur.fd(25)
        tur.right(90)
        tur.fd(25)
    elif letter == "E":
        tur.setheading(0)
        tur.pd()
        tur.fd(25)
        tur.bk(25)
        tur.right(90)
        tur.fd(12.5)
        tur.left(90)
        tur.fd(10)
        tur.bk(10)
        tur.right(90)
        tur.fd(12.5)
        tur.left(90)
        tur.fd(25)
    elif letter == "F":
        tur.setheading(0)
        tur.pd()
        tur.right(90)
        tur.fd(25)
        tur.left(180)
        tur.fd(12.5)
        tur.right(90)
        tur.fd(25)
        tur.bk(25)
        tur.left(90)
        tur.fd(12.5)
        tur.right(90)
        tur.fd(25)
    elif letter == "G":
        tur.setheading(0)
        tur.pd()
        tur.fd(25)
        tur.bk(25)
        tur.right(90)
        tur.fd(25)
        tur.left(90)
        tur.fd(25)
        tur.left(90)
        tur.fd(12.5)
        tur.left(90)
        tur.fd(12.5)	
    elif letter == "H":
	    tur.setheading(0)
	    tur.fd(90)
	    tur.right(180)
	    tur.fd(45)
	    tur.right(90)
	    tur.fd(45)
	    tur.right(90)
	    tur.fd(45)
	    tur.right(180)
	    tur.fd(90)
	    tur.pu()
            tur.fd(5)
            tur.right(90)
            tur.fd(5)
            tur.pd()
    elif letter == "I":
	    tur.setheading(0)
	    tur.fd(60)
	    tur.right(180)
	    tur.fd(30)
	    tur.left(90)
	    tur.fd(90)
	    tur.left(90)
	    tur.fd(30)
	    tur.right(180)
	    tur.fd(60)
	    tur.pu()
            tur.fd(5)
            tur.right(90)
            tur.fd(5)
            tur.pd()
    elif letter == "J":
	    tur.setheading(0)
	    tur.fd(30)
	    tur.right(90)
	    tur.fd(90)
	    tur.right(45)
	    tur.fd(15)
	    tur.right(90)
	    tur.fd(15)
	    tur.pu()
            tur.fd(5)
            tur.right(90)
            tur.fd(5)
            tur.pd()
    elif letter == "K":
	    tur.setheading(0)
	    tur.right(90)
	    tur.fd(90)
	    tur.right(180)
	    tur.fd(45)
	    tur.right(45)
	    tur.fd(45)
	    tur.right(180)
	    tur.fd(45)
	    tur.left(90)
	    tur.fd(45)
	    tur.pu()
            tur.fd(5)
            tur.right(90)
            tur.fd(5)
            tur.pd()
    elif letter == "L":
	    tur.setheading(0)
	    tur.right(90)
	    tur.fd(90)
	    tur.left(90)
	    tur.fd(60)
	    tur.pu()
            tur.fd(5)
            tur.right(90)
            tur.fd(5)
            tur.pd()
    elif letter == "M":
	    tur.setheading(0)
	    tur.right(90)
	    tur.fd(90)
	    tur.right(180)
	    tur.fd(90)
	    tur.right(135)
	    tur.fd(45)
	    tur.left(90)
	    tur.fd(45)
	    tur.right(135)
	    tur.fd(90)
	    tur.pu()
            tur.fd(5)
            tur.right(90)
            tur.fd(5)
            tur.pd()
        elif letter == "N":
            tur.setheading(0)
            tur.pd()
            tur.left(90)
            tur.fd(30)
            tur.right(135)
            tur.fd(40)
            tur.left(45)
            tur.fd(5)
            tur.left(90)
            tur.fd(30)
            tur.pu()
            tur.right(90)
            tur.fd(15)
    elif letter == "O":
	    tur.setheading(0)
	    tur.pd()
	    tur.fd(40)
	    tur.left(90)
	    tur.fd(50)
	    tur.left(90)
	    tur.fd(40)
	    tur.left(90)
	    tur.fd(50)
	    tur.left(180)
	    tur.fd(50)
	    tur.right(90)
	    tur.fd(40)
	    tur.pu()
	    tur.fd(15)
    elif letter == "P":
	    tur.setheading(0)
	    tur.pd()
	    tur.fd(40)
	    tur.left(90)
	    tur.fd(50)
	    tur.left(90)
	    tur.fd(40)
	    tur.left(90)
	    tur.fd(100)
	    tur.pu()
	    tur.left(180)
	    tur.fd(100)
	    tur.right(90)
	    tur.fd(55)
	    
    elif letter == "Q":
	    tur.setheading(0)
	    tur.pd()
	    tur.fd(40)
	    tur.left(90)
	    tur.fd(50)
	    tur.left(90)
	    tur.fd(40)
	    tur.left(90)
	    tur.fd(50)
	    tur.left(90)
	    tur.fd(40)
	    tur.right(45)
	    tur.fd(15)
	    tur.left(180)
	    tur.fd(30)
	    tur.pu()
	    tur.left(180)
	    tur.fd(15)
	    tur.left(135)
	    tur.fd(50)
	    tur.right(90)
	    tur.fd(15)
	    
    elif letter == "R":
	    tur.setheading(0)
	    tur.pd()
	    tur.fd(40)
	    tur.left(90)
	    tur.fd(50)
	    tur.left(90)
	    tur.fd(40)
	    tur.left(90)
	    tur.fd(100)
	    tur.right(180)
	    tur.fd(50)
	    tur.right(135)
	    tur.fd(70)
	    tur.pu()
	    tur.left(180)
	    tur.fd(70)
	    tur.right(135)
	    tur.fd(40)
	    tur.left(90)
	    tur.fd(50)
	    tur.right(90)
	    tur.fd(15)
	    
	    
    elif letter == "S":
	    tur.setheading(0)
	    tur.pd()
	    tur.left(90)
	    tur.fd(30)
	    tur.right(90)
	    tur.fd(30)
	    tur.right(180)
	    tur.fd(30)
	    tur.left(90)
	    tur.fd(30)
	    tur.left(90)
	    tur.fd(30)
	    tur.right(90)
	    tur.fd(30)
	    tur.right(90)
	    tur.fd(32)
	    tur.right(180)
	    tur.fd(32)
	    tur.left(90)
	    tur.fd(30)
	    tur.left(90)
	    tur.fd(30)
	    tur.right(90)
	    tur.fd(30)
	    tur.right(90)
	    tur.fd(30)
	    tur.pu()
	    
     elif letter == "T":
        tur.setheading(0)
        tur.pd()
        tur.left(90)
        tur.fd(50)
        tur.right(90)
        tur.fd(20)
        tur.bk(40)
        tur.fd(40)
    elif letter == "U":
        tur.setheading(0)
        tur.pd()
        tur.left(90)
        tur.fd(50)
        tur.right(180)
        tur.fd(50)
        tur.left(90)
        tur.fd(40)
        tur.left(90)
        tur.fd(50)

    elif letter == "V":
        tur.setheading(0)
        tur.pd()
        tur.left(135)
        tur.fd(50)
        tur.right(180)
        tur.fd(50)
        tur.left(90)
        tur.fd(50)
    
    elif letter == "W":
        tur.setheading(0)
        tur.pd()
        tur.left(135)
        tur.fd(50)
        tur.right(180)
        tur.fd(50)
        tur.left(90)
        tur.fd(50)
        tur.right(90)
        tur.fd(50)
        tur.left(90)
        tur.fd(50)
    elif letter == "X":
        tur.setheading(0)
        tur.pd()
        tur.left(45)
        tur.fd(50)
        tur.left(135)
        tur.pu()
        tur.fd(25)
        tur.pd()
        tur.left(135)
        tur.fd(50)
        
    elif letter == "Y":
        tur.setheading(0)
        tur.pd()
        tur.left(90)
        tur.fd(50)
        tur.left(45)
        tur.fd(25)
        tur.left(180)
        tur.fd(25)
        tur.left(90)
        tur.fd(25)
    elif letter == "Z":
        tur.setheading(0)
        tur.pd()
        tur.fd(30)
        tur.left(180)
        tur.fd(30)
        tur.right(135)
        tur.fd(50)
        tur.left(135)
        tur.fd(30)
        
    elif letter == "Ax":
        # code here
        tur.forward(40)
		
    else:
        turtleLetter("box",tur)
	
2






window = turtle.Screen()
tur = turtle.Turtle()
tur.speed(1)
#turtleLetter("box",tur)
turtleLetter("A",tur)


window.exitonclick()
